/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function setup() {
    return invoke()<boolean>("setup")
}

export function fetchUrls() {
    return invoke()<null>("fetch_urls")
}

export function getDevices() {
    return invoke()<null>("get_devices")
}

export function getPrivateIpAddresses() {
    return invoke()<string[]>("get_private_ip_addresses")
}

export function startHostedNetwork(name: string, password: string) {
    return invoke()<boolean>("start_hosted_network", { name,password })
}

export function isHostedNetwork() {
    return invoke()<boolean>("is_hosted_network")
}

export function stopHostedNetwork() {
    return invoke()<boolean>("stop_hosted_network")
}

export function installDrivers() {
    return invoke()<boolean>("install_drivers")
}

export function createDisplay(config: VirtualDisplayConfig) {
    return invoke()<boolean>("create_display", { config })
}

export function updateDisplay(displayId: number, config: VirtualDisplayConfig) {
    return invoke()<boolean>("update_display", { displayId,config })
}

export function removeDisplay(displayId: number) {
    return invoke()<boolean>("remove_display", { displayId })
}

export function removeAllDisplays() {
    return invoke()<boolean>("remove_all_displays")
}

export type VirtualDisplayConfig = { name: string; width: number; height: number; refresh_rate: number }
