// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async checkSystemRequirements() : Promise<CompatibilityReport> {
    return await TAURI_INVOKE("check_system_requirements");
},
async checkPermissions() : Promise<PermissionStatus[]> {
    return await TAURI_INVOKE("check_permissions");
},
async requestPermission(key: string) : Promise<boolean> {
    return await TAURI_INVOKE("request_permission", { key });
},
async openPermissionSettings(key: string) : Promise<void> {
    await TAURI_INVOKE("open_permission_settings", { key });
},
async setup() : Promise<boolean> {
    return await TAURI_INVOKE("setup");
},
async setSessionCredentials(sessionId: string, otp: string) : Promise<void> {
    await TAURI_INVOKE("set_session_credentials", { sessionId, otp });
},
async registerCloudSession(sessionId: string) : Promise<void> {
    await TAURI_INVOKE("register_cloud_session", { sessionId });
},
async unregisterCloudSession() : Promise<void> {
    await TAURI_INVOKE("unregister_cloud_session");
},
async getCloudStatus() : Promise<CloudStatusChange> {
    return await TAURI_INVOKE("get_cloud_status");
},
async exitApp() : Promise<void> {
    await TAURI_INVOKE("exit_app");
},
async setWindowZoom(factor: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_window_zoom", { factor }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getUsername() : Promise<string> {
    return await TAURI_INVOKE("get_username");
},
async setAvatar(bytes: number[]) : Promise<boolean> {
    return await TAURI_INVOKE("set_avatar", { bytes });
},
async getAvatar() : Promise<number[] | null> {
    return await TAURI_INVOKE("get_avatar");
},
async removeAvatar() : Promise<boolean> {
    return await TAURI_INVOKE("remove_avatar");
},
async getNetworkAdapters() : Promise<NetworkInfo[]> {
    return await TAURI_INVOKE("get_network_adapters");
},
async watchForNetworkChanges() : Promise<void> {
    await TAURI_INVOKE("watch_for_network_changes");
},
async startHostedNetwork(name: string, password: string) : Promise<boolean> {
    return await TAURI_INVOKE("start_hosted_network", { name, password });
},
async stopHostedNetwork() : Promise<boolean> {
    return await TAURI_INVOKE("stop_hosted_network");
},
async isHostedNetwork() : Promise<boolean> {
    return await TAURI_INVOKE("is_hosted_network");
},
async isWifiOn() : Promise<boolean> {
    return await TAURI_INVOKE("is_wifi_on");
},
async turnOnWifi() : Promise<boolean> {
    return await TAURI_INVOKE("turn_on_wifi");
},
async installDrivers() : Promise<boolean> {
    return await TAURI_INVOKE("install_drivers");
},
async removeDrivers() : Promise<boolean> {
    return await TAURI_INVOKE("remove_drivers");
},
async installAudioDriver() : Promise<string> {
    return await TAURI_INVOKE("install_audio_driver");
},
async uninstallAudioDriver() : Promise<string> {
    return await TAURI_INVOKE("uninstall_audio_driver");
},
async audioDriverStatus() : Promise<string> {
    return await TAURI_INVOKE("audio_driver_status");
},
async setLegacyVolumeKeyProxy(enabled: boolean) : Promise<void> {
    await TAURI_INVOKE("set_legacy_volume_key_proxy", { enabled });
},
async setDeviceOverride(ip: string, scale: number, orientation: string, refreshRate: number, videoScale: number, videoQuality: number, controlEnabled: boolean, dpr: number, audioEnabled: boolean) : Promise<void> {
    await TAURI_INVOKE("set_device_override", { ip, scale, orientation, refreshRate, videoScale, videoQuality, controlEnabled, dpr, audioEnabled });
},
async refreshDeviceStream(ip: string) : Promise<boolean> {
    return await TAURI_INVOKE("refresh_device_stream", { ip });
},
async setDeviceAudioOutput(ip: string, deviceId: string) : Promise<void> {
    await TAURI_INVOKE("set_device_audio_output", { ip, deviceId });
},
async getDeviceAudioOutputs(ip: string) : Promise<AudioOutputsReport> {
    return await TAURI_INVOKE("get_device_audio_outputs", { ip });
},
async removeDeviceOverride(ip: string) : Promise<void> {
    await TAURI_INVOKE("remove_device_override", { ip });
},
async setDeviceBanned(token: string, ip: string, banned: boolean) : Promise<void> {
    await TAURI_INVOKE("set_device_banned", { token, ip, banned });
},
async setDeviceApproved(token: string, approved: boolean) : Promise<void> {
    await TAURI_INVOKE("set_device_approved", { token, approved });
},
async setDisconnectGrace(seconds: number) : Promise<void> {
    await TAURI_INVOKE("set_disconnect_grace", { seconds });
},
async getDisconnectGrace() : Promise<number> {
    return await TAURI_INVOKE("get_disconnect_grace");
},
async getDisplayCapacity() : Promise<DisplayCapacity> {
    return await TAURI_INVOKE("get_display_capacity");
},
async setTurnConfig(urls: string, username: string, credential: string) : Promise<void> {
    await TAURI_INVOKE("set_turn_config", { urls, username, credential });
},
async getTurnConfig() : Promise<TurnConfig> {
    return await TAURI_INVOKE("get_turn_config");
},
async setServerPorts(httpPort: number, httpsPort: number) : Promise<ServerPorts> {
    return await TAURI_INVOKE("set_server_ports", { httpPort, httpsPort });
},
async getServerPorts() : Promise<ServerPorts> {
    return await TAURI_INVOKE("get_server_ports");
},
async setDisableGpuEncode(disabled: boolean) : Promise<void> {
    await TAURI_INVOKE("set_disable_gpu_encode", { disabled });
},
async getDisableGpuEncode() : Promise<boolean> {
    return await TAURI_INVOKE("get_disable_gpu_encode");
},
async getLogBacklog() : Promise<string[]> {
    return await TAURI_INVOKE("get_log_backlog");
}
}

/** user-defined events **/


export const events = __makeEvents__<{
cloudStatusChange: CloudStatusChange,
deviceAudioOutputs: DeviceAudioOutputs,
deviceJoin: DeviceJoin,
deviceModify: DeviceModify,
deviceModifyAction: DeviceModifyAction,
deviceRemove: DeviceRemove,
deviceRemoveAction: DeviceRemoveAction,
hostedNetworkNoPassword: HostedNetworkNoPassword,
joinAttemptsPaused: JoinAttemptsPaused,
logLine: LogLine,
networkChange: NetworkChange,
sessionIdChange: SessionIdChange
}>({
cloudStatusChange: "cloud-status-change",
deviceAudioOutputs: "device-audio-outputs",
deviceJoin: "device-join",
deviceModify: "device-modify",
deviceModifyAction: "device-modify-action",
deviceRemove: "device-remove",
deviceRemoveAction: "device-remove-action",
hostedNetworkNoPassword: "hosted-network-no-password",
joinAttemptsPaused: "join-attempts-paused",
logLine: "log-line",
networkChange: "network-change",
sessionIdChange: "session-id-change"
})

/** user-defined constants **/



/** user-defined types **/

export type AudioOutput = { id: string; label: string }
export type AudioOutputsReport = { supported: boolean; outputs: AudioOutput[]; selected: string }
export type CloudStatusChange = { state: string; detail: string }
export type CompatibilityReport = { os_name: string; os_version: string; min_os_version: string; os_supported: boolean; unsupported_apis: UnsupportedApi[]; audio_backend: string; display_backend: string }
export type Device = { ip: string; token: string; name: string; scale: number; orientation: string; refreshRate: number; videoScale: number; videoQuality: number; remoteControl: boolean; systemAudio: boolean; os: string; screenSize: string; dpr: number; maxDpr: number }
export type DeviceAudioOutputs = { ip: string; supported: boolean; outputs: AudioOutput[]; selected: string }
export type DeviceJoin = Device
export type DeviceModify = Device
export type DeviceModifyAction = Device
export type DeviceRemove = Device
export type DeviceRemoveAction = Device
export type DisplayCapacity = { max: number | null; in_use: number; full: boolean; backend: string }
export type HostedNetworkNoPassword = null
export type JoinAttemptsPaused = { retryAfterSecs: number }
export type LogLine = string
export type NetworkChange = null
export type NetworkInfo = { network_name: string; interface_index: number; ip_addresses: string[] }
export type PermissionStatus = { key: string; name: string; description: string; granted: boolean; required: boolean }
export type ServerPorts = { http: number; https: number }
export type SessionIdChange = { sessionId: string }
export type TurnConfig = { urls: string; username: string; credential: string }
export type UnsupportedApi = { name: string; description: string; required_version: string; severity: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
