
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async setup() : Promise<boolean> {
    return await TAURI_INVOKE("setup");
},
async getDevices() : Promise<void> {
    await TAURI_INVOKE("get_devices");
},
async setCurrentUser(currentUser: string) : Promise<void> {
    await TAURI_INVOKE("set_current_user", { currentUser });
},
async getNetworkAdapters() : Promise<NetworkInfo[]> {
    return await TAURI_INVOKE("get_network_adapters");
},
async startHostedNetwork(name: string, password: string) : Promise<boolean> {
    return await TAURI_INVOKE("start_hosted_network", { name, password });
},
async stopHostedNetwork() : Promise<boolean> {
    return await TAURI_INVOKE("stop_hosted_network");
},
async isHostedNetwork() : Promise<boolean> {
    return await TAURI_INVOKE("is_hosted_network");
},
async installDrivers() : Promise<boolean> {
    return await TAURI_INVOKE("install_drivers");
},
async createDisplay(config: VirtualDisplayConfig) : Promise<Result<number, null>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_display", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateDisplay(displayId: number, config: VirtualDisplayConfig) : Promise<Result<boolean, null>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_display", { displayId, config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeDisplay(displayId: number) : Promise<Result<boolean, null>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_display", { displayId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeAllDisplays() : Promise<Result<boolean, null>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_all_displays") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
deviceJoin: DeviceJoin,
deviceModify: DeviceModify,
deviceModifyAction: DeviceModifyAction,
deviceRemove: DeviceRemove,
deviceRemoveAction: DeviceRemoveAction,
networkChange: NetworkChange
}>({
deviceJoin: "device-join",
deviceModify: "device-modify",
deviceModifyAction: "device-modify-action",
deviceRemove: "device-remove",
deviceRemoveAction: "device-remove-action",
networkChange: "network-change"
})

/** user-defined constants **/



/** user-defined types **/

export type Device = { ip: string; name: string; scale: number; orientation: string; refreshRate: number; os: string; screenSize: string }
export type DeviceJoin = Device
export type DeviceModify = Device
export type DeviceModifyAction = Device
export type DeviceRemove = Device
export type DeviceRemoveAction = Device
export type NetworkChange = null
export type NetworkInfo = { network_name: string; interface_index: number; ip_addresses: string[] }
export type VirtualDisplayConfig = { name: string; width: number; height: number; refresh_rate: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
